# Generated by Django 4.2.5 on 2023-10-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_useractivity_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelbotdata',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='travelbotdata',
            name='question',
        ),
        migrations.RemoveField(
            model_name='travelbotdata',
            name='topic_name',
        ),
        migrations.AddField(
            model_name='travelbotdata',
            name='Contact_Email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travelbotdata',
            name='Contact_First_Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travelbotdata',
            name='Contact_Last_Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travelbotdata',
            name='Contact_Number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travelbotdata',
            name='Description_of_the_Experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travelbotdata',
            name='Is_The_Guide_Included_in_the_cost',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travelbotdata',
            name='Location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travelbotdata',
            name='Maximum_Pax_per_cost',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travelbotdata',
            name='Tag_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travelbotdata',
            name='Tag_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travelbotdata',
            name='Tag_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travelbotdata',
            name='Tag_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travelbotdata',
            name='Tag_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travelbotdata',
            name='Tag_6',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travelbotdata',
            name='Time_of_Visit_hours',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travelbotdata',
            name='Vendor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travelbotdata',
            name='net_Cost_Per_Person_Adult',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travelbotdata',
            name='net_Cost_Per_Person_Child_Senior',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travelbotdata',
            name='net_Cost_by_Experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travelbotdata',
            name='net_Cost_by_Hour',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
