# Generated by Django 4.2.5 on 2023-10-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_questionandanswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionAndAnswer',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='topic',
            field=models.TextField(default=2, max_length=1000),
            preserve_default=False,
        ),
    ]
