# Generated by Django 4.2.5 on 2023-10-26 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_topics_alter_useractivity_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topics',
            old_name='user_id',
            new_name='user',
        ),
    ]
