# Generated by Django 4.2.5 on 2023-10-26 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_topics_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='topic_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.topics'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='topic',
            field=models.TextField(max_length=1000),
        ),
    ]
