# Generated by Django 4.2.6 on 2023-11-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_topics_vendor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='vendor_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
