# Generated by Django 4.2.5 on 2023-11-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_topics_vendor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
