# Generated by Django 4.2.6 on 2023-12-05 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_topics_vendor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetailGethringForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('numberOfTour', models.IntegerField()),
                ('client_firstName', models.CharField(max_length=255)),
                ('client_lastName', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('datesOfTravel', models.CharField(max_length=255)),
                ('numberOfTravellers', models.IntegerField()),
                ('agesOfTravellers', models.CharField(max_length=255)),
                ('lengthToStay', models.CharField(max_length=255)),
                ('select_budget', models.TextField(choices=[('Up to €5000', 'Up to €5000'), ('Between €5000 - €10,000', 'Between €5000 - €10,000'), ('Between €10,000 - €15,000', 'Between €10,000 - €15,000'), ('Between €15,000 - €20,000', 'Between €15,000 - €20,000'), ('€20,000 and over', '€20,000 and over'), ('Other', 'Other')])),
                ('flightArrivalTime', models.TextField()),
                ('flightArrivalNumber', models.CharField(max_length=255)),
                ('flightDepartureTime', models.TextField()),
                ('flightDepartureNumber', models.CharField(max_length=255)),
                ('accommodation_specific', models.TextField(choices=[('Knights', 'Knights'), ('Artisans', 'Artisans'), ('Food & Wine', 'Food & Wine'), ('Nobile Malta', 'Nobile Malta'), ('Exclusive/Private/After hours', 'Exclusive/Private/After hours'), ('Shopping', 'Shopping'), ('Catholic', 'Catholic'), ('Heritage or Culture/UNESCO', 'Heritage or Culture/UNESCO'), ('Art', 'Art'), ('Soft Adventure', 'Soft Adventure'), ('Active', 'Active'), ('Water Activity', 'Water Activity'), ('WWII', 'WWII'), ('Family', 'Family'), ('Music', 'Music'), ('Gozo', 'Gozo'), ('Nature/Outdoors', 'Nature/Outdoors'), ('Nightlife', 'Nightlife')])),
                ('malta_experience', models.TextField(choices=[('Not more than 4 Hours', 'Not more than 4 Hours'), ('Not more than 6 Hours', 'Not more than 6 Hours'), ('Not more than 8 Hours', 'Not more than 8 Hours')])),
                ('start_time', models.TextField(choices=[('08:30', '08:30'), ('09:00', '09:00'), ('09:30', '09:30'), ('10:00', '10:00'), ('Other', 'Other')])),
                ('lunch_time', models.TextField(choices=[('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('Other', 'Other')])),
                ('dinner_time', models.TextField(choices=[('19:00', '19:00'), ('19:30', '19:30'), ('20:00', '20:00'), ('20:30', '20:30'), ('Other', 'Other')])),
                ('issues_n_phobias', models.TextField(choices=[('Claustrophobic', 'Claustrophobic'), ('Vegan', 'Vegan'), ('Does not drink', 'Does not drink'), ('Does not swim/like being on the water', 'Does not swim/like being on the water'), ('No alcohol', 'No alcohol'), ('Jewish', 'Jewish'), ('Vegetarian', 'Vegetarian'), ('Muslim', 'Muslim')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
