# Generated by Django 4.2.6 on 2023-12-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_userdetailgethringform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetailgethringform',
            name='flightArrivalNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdetailgethringform',
            name='flightArrivalTime',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetailgethringform',
            name='flightDepartureNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdetailgethringform',
            name='flightDepartureTime',
            field=models.TextField(blank=True, null=True),
        ),
    ]
