# Generated by Django 4.2.6 on 2023-12-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_userdetailgethringform_flightarrivalnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetailgethringform',
            name='numberOfTour',
            field=models.IntegerField(unique=True),
        ),
    ]
