# Generated by Django 4.2.6 on 2023-12-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_userdetailgethringform_numberoftour'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetailgethringform',
            name='other_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetailgethringform',
            name='accommodation_specific',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userdetailgethringform',
            name='issues_n_phobias',
            field=models.TextField(),
        ),
    ]
