# Generated by Django 4.2.6 on 2023-12-26 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_userdetailgethringform_other_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetailgethringform',
            name='lengthToStay',
        ),
    ]
